FROM postgres:16

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    postgresql-server-dev-16 \
    flex \
    bison \
    && rm -rf /var/lib/apt/lists/*

RUN cd /tmp \
    && git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install

RUN cd /tmp \
    && git clone https://github.com/apache/age.git \
    && cd age \
    && git checkout release/PG16/1.5.0 \
    && make \
    && make install

COPY init-db.sql /docker-entrypoint-initdb.d/01-init-db.sql
COPY init-age.sql /docker-entrypoint-initdb.d/02-init-age.sql

RUN rm -rf /tmp/pgvector /tmp/age

ENV POSTGRES_DB=lightrag
ENV POSTGRES_USER=lightrag
ENV POSTGRES_PASSWORD=lightrag_password
